name: Continuous Integration (CI)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Testing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["20.x", "22.x"]

    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies Next.JS
        run: npm install
        working-directory: ./client

      - name: Run tests Next.JS 
        run: npm run test
        working-directory: ./client

      - name: Install dependencies Express.JS
        run: npm install
        working-directory: ./server

      - name: Run Prisma generate
        run: npx prisma generate
        working-directory: ./server
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      # - name: Run tests Express.JS
      #   run: npm run test
      #   working-directory: ./server
      #   env:
      #     DATABASE_URL: ${{ secrets.DATABASE_URL }}
